apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Argo Rollouts Extension 활성화
  extension.config: |
    extensions:
      - name: argo-rollouts
        backend:
          services:
            - url: http://infra-argo-rollouts-dashboard.argo-rollouts:3100/api/v1
